version: "3"

services:
  shop:
    build:
      context: .
    container_name: shop
    image: shop:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - shop-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shop
      - SPRING_DATASOURCE_USERNAME=akanay
      - SPRING_DATASOURCE_PASSWORD=Frfyfq19071981
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql:3306
      - SPRING_PROFILES_ACTIVE=form

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      - MYSQL_USER=akanay
      - MYSQL_PASSWORD=Frfyfq19071981
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
      - shop-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

networks:
  shop-network:
volumes:
  database:






