server:
  port: 8080
  error:
    path: /error
logging:
  level:
    com.example.shop: DEBUG

    org:
      springframework:
        jdbc:
          core:
            jdbcTemplate: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: akanay
    password: Frfyfq19071981
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    url: jdbc:mysql://localhost:3306/
    user: akanay
    password: Frfyfq19071981
    driver-class-name: com.mysql.cj.jdbc.Driver
    locations: classpath:/db.migration
    schemas: shop
    baseline-on-migrate: true
    baseline-version: 0

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true






